/* Autogenerated with DRAKON Editor 1.11 */
#include "test.h"


static void main(void);

static void test1(void);

static void test2(void);

static void test3(void);

static void main(void) {
    /* item 33 */
    printf("test0\n");
    /* item 15 */
    test1
    /* item 16 */
    test2();
    /* item 17 */
    test3
    return;
    
}

static void test1(void) {
    /* item 34 */
    printf("test1\n");
    return;
    
}

static void test2(void) {
    /* item 35 */
    printf("test2\n");
    return;
    
}

static void test3(void) {
    /* item 36 */
    printf("test3\n");
    return;
    
}



