/* Autogenerated with DRAKON Editor 1.11 */
#ifndef MEGABOT_H43586
#define MEGABOT_H43586

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <getopt.h>
#include <malloc.h>
#include <string.h>
#include <signal.h>
#include <math.h>
#include <time.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include "libircclient/libircclient.h"

typedef struct {
  char *server;
  char *channel;
  char *brainfile;
} PROGRAM_OPT;
int main(
    int argc,
    char **argv
);

int parse_command_line_option(
    int argc,
    char **argv,
    PROGRAM_OPT *program_opt
);


#endif

