/* Autogenerated with DRAKON Editor 1.11 */
#ifndef MEGABOT_H27220
#define MEGABOT_H27220

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <getopt.h>
#include <malloc.h>
#include <string.h>
#include <signal.h>
#include <math.h>
#include <time.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
int main(
    int argc,
    char **argv
);


#endif

